### ISSUE TITLE
Adding a blank settings.py

### ISSUE THREAD

**Issue by jbz-dev** [rhyst/olm#2]
Hi,

I've just discovered `olm` and it sounds really great :+1: 

I'm not a dev but really want to learn a programming language and I settle on Python.

Olm seems really simple, without fuss and I will follow the development and convert my Hugo blog to it.

However after a `pip install olm` it could be nice to have a `quickstart` command that generate directories and `settings.py`. What do you think about that ?

**Comment by rhyst** [comment]
Hey Bridouz,

It's really cool to have someone find this! I have a todo list [here](https://github.com/rhyst/olm/blob/master/TODO.md) and I have added your quickstart command  suggestion.

I think it should generate a site that builds with example an article, page, theme and plugin. Something quite basic and easy to modify.

I will try to implement this soon, so thank you for suggestion.

**Comment by rhyst** [comment]
Added --init command to create basic example site [2f9ac141](https://github.com/rhyst/olm/commit/2f9ac14111e819c084e05aa791998371c5374a61)
