### ISSUE TITLE
[ Proposal ] Syntaxe Highlighting Plugin

### ISSUE THREAD

**Issue by jbz-dev** [rhyst/olm#5]
Because I'm a beginner in Python I dont know (yet) how to write plugins.

Is possible to write one to enable `Pygments` ?

I saw a plugin for mistune [Highlight](https://github.com/lepture/mistune-contrib/blob/master/mistune_contrib/highlight.py)

**Comment by rhyst** [comment]
Sure, I will use this as the example plugin for the new init command shortly.

**Comment by rhyst** [comment]
This is now included as an example plugin when using the quickstart command. To install on an existing site:
- upgrade olm to > 0.0.35
- create a `plugins/pygment_plugin/pygment_plugin.py` file in your site with the following content:
```python
import re
from olm.signals import signals
from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import HtmlFormatter
def replace(match):
    language = match.group(2)
    lexer = get_lexer_by_name(language, stripall=True)
    formatter = HtmlFormatter(linenos=True, noclasses=True)
    return highlight(match.group(3), lexer, formatter)
def add_pygments(self, context, source):
    pattern = re.compile(r'(```)(.*)\\n([\w\W]*)(```)', re.MULTILINE)
    source.content = pattern.sub(replace, source.content)
def register():
    return [
        (signals.BEFORE_MD_CONVERT, add_pygments)
    ]
```
- add the following to your `settings.py`
```
    "PLUGINS_FOLDER": "{{BASE_FOLDER}}/plugins",
    "PLUGINS": ['pygment_plugin']
```
